import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col justify-center items-center text-center">
      <Head>
        <title>NEXT APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="">
        HEADER
      </header>
      <main>
        <div>
          Don's Portfolio
        </div>
        <div>
         Let&apos;s get started!
        </div>
      </main>

      <footer>
        FOOTER
      </footer>
    </div>
  );
};

export default Home;
