import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NEXT APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.footer}>
        HEADER
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          NEXT + TS
        </h1>
        <div className={styles.card}>
          <h2>Let&apos;s get started!</h2>
        </div>
      </main>

      <footer className={styles.footer}>
        FOOTER
      </footer>
    </div>
  );
};

export default Home;
